Fix check assert tests
Summary
-------

Spurious,timing-related errors were seen in testlib_tests.
See issue #347.  The root of the problem is that the subordinate process
sometimes exits with data left on the pipe, which the parent process neglects
to fully read. It happens rarely but happens with increased frequency if the
system is under load.

This MR fixes the issue by ensuring all data is drained from the pipes to the
subordinate process before returning. In my tests (with extra prints) I
can confirm that sometimes the "expected message" remains stuck on the pipe
to the subordinate process if the system is under load, e.g.:

```
Partial read from 5 = "test_bitcoin: ../src/test/testlib_tests.cpp:25: testlib_tests::check_assert_test::test_method()::<lambda()>: Assertion `!"right message"' failed.
```

This MR closes #347.

Test Plan
---------

Do the below first against master (to reproduce issue) then against this
MR to see it no longer happening:

- Build in debug mode (e.g. `-DCMAKE_BUILD_TYPE=Debug`)
- Run this in a loop from 1 console: 
  `ninja test_bitcoin && let i=0; while src/test/test_bitcoin -t testlib_tests -l warning; echo $i; do let i++; done`
- In another console, put the machine under heavy load

You should see the spurious failure happen if you run the above for a while.
The failures look like the error messages seen in #347 e.g.:

```
../src/test/testlib_tests.cpp(32): error: in "testlib_tests/check_assert_test": Failed to trap the appropriate assert for: "(static_cast <bool> (!"expected message") ? void (0) : __assert_fail ("!\"expected message\"", "../src/test/testlib_tests.cpp", 32, __extension__ __PRETTY_FUNCTION__))"

*** 1 failure is detected in the test module "Bitcoin Cash Node unit tests"
```

If you repeat the above procedure for this MR, you should see no such failures ever.